name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true

jobs:
  check-environment:
    name: Check environment
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
